YangFuDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
  path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('signup/', views.SignUp.as_view(), name='signup'),
]

yfcases/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name="yfcase"

urlpatterns = [
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  path('',views.YfcaseListView.as_view(),name="home" ),
  path('yfcase/<int:pk>/',views.YfcaseDetailView.as_view(),name="yfcase_detail" ),
  path('yfcase/new/',views.YfcaseCreateView.as_view(),name="yfcase_new" ),
  path('yfcase/<int:pk>/edit/',views.YfcaseUpdateView.as_view(),name="yfcase_edit" ),
  path('yfcase/<int:pk>/delete/',views.YfcaseDeleteView.as_view(),name="yfcase_delete" ),
  path('land/new/',views.LandCreateView.as_view(),name="land_new" ),
  path('land/<int:pk>/edit/',views.LandUpdateView.as_view(),name="land_edit" ),
  path('land/<int:pk>/delete/',views.LandDeleteView.as_view(),name="land_delete" ),
  path('build/new/',views.BuildCreateView.as_view(),name="build_new" ),
  path('build/<int:pk>/edit/',views.BuildUpdateView.as_view(),name="build_edit" ),
  path('build/<int:pk>/delete/',views.BuildDeleteView.as_view(),name="build_delete" ),
  path('auction/new/',views.AuctionCreateView.as_view(),name="auction_new" ),
  path('auction/<int:pk>/edit/',views.AuctionUpdateView.as_view(),name="auction_edit" ),
  path('survey/new/',views.SurveyCreateView.as_view(),name="survey_new" ),
  path('survey/<int:pk>/edit/',views.SurveyUpdateView.as_view(),name="survey_edit" ),
  path('objectbuild/new/',views.ObjectBuildCreateView.as_view(),name="objectbuild_new" ),
  path('objectbuild/<int:pk>/edit/',views.ObjectBuildUpdateView.as_view(),name="objectbuild_edit" ),
  path('objectbuild/<int:pk>/delete/',views.ObjectBuildDeleteView.as_view(),name="objectbuild_delete" ),
  path('scorea/<int:pk>/edit/',views.ScoreAUpdateView.as_view(),name="score_a_edit" ),
  path('scoreb/<int:pk>/edit/',views.ScoreBUpdateView.as_view(),name="score_b_edit" ),
  path('scorec/<int:pk>/edit/',views.ScoreCUpdateView.as_view(),name="score_c_edit" ),
  path('scorea/<int:pk>/delete/',views.ScoreADeleteView.as_view(),name="score_a_delete" ),
  path('scoreb/<int:pk>/delete/',views.ScoreBDeleteView.as_view(),name="score_b_delete" ),
  path('scorec/<int:pk>/delete/',views.ScoreCDeleteView.as_view(),name="score_c_delete" ),
  path('clicklist/new/',views.ClickListCreateView.as_view(),name="clicklist_new" ),
  path('clicklist/<int:pk>/edit/',views.ClickListUpdateView.as_view(),name="clicklist_edit" ),
  path('regionalhead/new/',views.RegionalHeadCreateView.as_view(),name="regionalhead_new" ),
  path('regionalhead/<int:pk>/edit/',views.RegionalHeadUpdateView.as_view(),name="regionalhead_edit" ),
  path('regionalhead/<int:pk>/delete/',views.RegionalHeadDeleteView.as_view(),name="regionalhead_delete" ),
  path('subsigntruea/new/',views.SubSigntrueACreateView.as_view(),name="subsigntruea_new" ),
  path('subsigntruea/<int:pk>/edit/',views.SubSigntrueAUpdateView.as_view(),name="subsigntruea_edit" ),
  path('subsigntruea/<int:pk>/delete/',views.SubSigntrueADeleteView.as_view(),name="subsigntruea_delete" ),
  path('subsigntrueb/new/',views.SubSigntrueBCreateView.as_view(),name="subsigntrueb_new" ),
  path('subsigntrueb/<int:pk>/edit/',views.SubSigntrueBUpdateView.as_view(),name="subsigntrueb_edit" ),
  path('subsigntrueb/<int:pk>/delete/',views.SubSigntrueBDeleteView.as_view(),name="subsigntrueb_delete" ),
  path('ajax/load-townships/', views.load_townships, name='ajax_load_townships'),
]

yfcases/models.py
from django.conf import settings
from django.db import models
from decimal import *
from datetime import datetime
import math
from django.db.models import Sum,Avg,Max

class City(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name
 
    class Meta:
        # managed = True
        db_table = 'yfcase_city'

class Township(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name
   
    class Meta:
        # managed = True
        db_table = 'yfcase_township'

class Yfcase(models.Model):
  yfcaseCaseNumber=models.CharField(u'案號(*)',max_length=100)
  yfcaseCompany=models.CharField(u'所屬公司',max_length=50,null=True,blank=True)
  yfcaseCity=models.ForeignKey(City,verbose_name = u'縣市',on_delete=models.SET_NULL,null=True)
  yfcaseTownship=models.ForeignKey(Township,verbose_name = u'鄉鎮區里', on_delete=models.SET_NULL, null=True)
  yfcaseBigSection=models.CharField(u'段號',max_length=10,null=True,blank=True)
  yfcaseSmallSection=models.CharField(u'小段',max_length=10,null=True,blank=True)
  yfcaseOtherAddress=models.CharField(u'其他住址',max_length=100,null=True,blank=True)
  yfcaseDebtor=models.CharField(u'債務人',max_length=10,null=True,blank=True)
  yfcaseCreditor=models.CharField(u'債權人',max_length=10,null=True,blank=True)
  user = models.ForeignKey('users.CustomUser',verbose_name = u'區域負責人', on_delete=models.CASCADE)

  def __str__(self):
    return self.yfcaseCaseNumber

  class Meta:
    # managed = True
    db_table = 'yfcase_yfcase'

  def get_regionalHead_username(self):
      return self.finaldecisions.regionalHead

  def get_user_username(self):
    return self.user.fullname

  def get_land_holding_point_area_total(self):
    newlist=[]
    try:
      landTotal = 0
      for land_item in self.lands.exclude(landHoldingPointAll=0):
        landTotal += land_item.landArea * land_item.landHoldingPointPersonal / land_item.landHoldingPointAll
      return landTotal
    except:
      newlist.append(0)

  def get_build_holding_point_area_total(self):
    try:
      buildTotal = 0
      for build_item in self.builds.exclude(buildHoldingPointAll=0):
        buildTotal += build_item.buildArea * build_item.buildHoldingPointPersonal / build_item.buildHoldingPointAll
      return buildTotal
    except ZeroDivisionError:
      return 0

  def get_build_first_not_add_and_not_public_area(self):
    return self.builds.exclude(buildTypeUse="增建-持分後坪數打對折").exclude(buildTypeUse="公設").first().get_build_holding_point_area()

  # 取得第一筆非公設、非增建的持分比
  def get_first_not_add_and_not_public_holding_point_rate(self):
    try:
      if self.builds.exclude(buildTypeUse="增建-持分後坪數打對折").exclude(buildTypeUse="公設").first():
        getFirstNotAddAndNotPublicHoldingPointPersonnal = self.builds.exclude(buildTypeUse="增建-持分後坪數打對折").exclude(buildTypeUse="公設").first().buildHoldingPointPersonal
        getFirstNotAddAndNotPublicHoldingPointAll = self.builds.exclude(buildTypeUse="增建-持分後坪數打對折").exclude(buildTypeUse="公設").first().buildHoldingPointAll
        return getFirstNotAddAndNotPublicHoldingPointPersonnal / getFirstNotAddAndNotPublicHoldingPointAll
    except ZeroDivisionError:
      return 0

  # (1)建物(非公設、非增建)持分後總面積
  def get_build_holding_point_area_group_total(self):
    newlist=[]
    try:
      getBuildHoldingPointAreaGroupTotal=0
      for getBuildHoldingPointAreaGroup in self.builds.exclude(buildTypeUse="增建-持分後坪數打對折").exclude(buildTypeUse="公設"):
        getBuildHoldingPointAreaGroupTotal = getBuildHoldingPointAreaGroupTotal + getBuildHoldingPointAreaGroup.get_build_holding_point_area()
      return getBuildHoldingPointAreaGroupTotal
    except:
      newlist.append(0)

  # (2)建物(公設)持分後總面積
  def get_build_holding_point_public_group_total(self):
    getBuildHoldingPointPublicGroupTotal=0
    for getBuildHoldingPointPublicGroup in self.builds.filter(buildTypeUse="公設"):
      getBuildHoldingPointPublicGroupTotal = getBuildHoldingPointPublicGroupTotal + getBuildHoldingPointPublicGroup.get_build_first_not_add_and_not_public_holding_point_area()
    return getBuildHoldingPointPublicGroupTotal

  # (3)建物(增建)持分後總面積
  def get_build_holding_point_add_group_total(self):
    try:
      getBuildHoldingPointAddGroupTotal=0
      for getBuildHoldingPointAddGroup in self.builds.filter(buildTypeUse="增建-持分後坪數打對折"):
        getBuildHoldingPointAddGroupTotal = getBuildHoldingPointAddGroupTotal + getBuildHoldingPointAddGroup.get_after_add_holding_point_area()
      return getBuildHoldingPointAddGroupTotal
    except ZeroDivisionError:
      return 0

  # 上述(1)+(2)+(3)
  def get_build_holding_point_after_group_total(self):
    newlist=[]
    try:
      return self.get_build_holding_point_area_group_total() + self.get_build_holding_point_public_group_total() + self.get_build_holding_point_add_group_total()
    except:
      newlist.append(0)

  def pbk(self):
    newlist=[]
    try:
      sumpbk=0
      countbk=0
      if self.auctions.all().filter(auctionFloorPriceFirst__gt=1000000):
        for objectbuild_item in self.objectbuilds.all():
          sumpbk += objectbuild_item.get_objectbuild_ping_price_abc_calculation()
          countbk += 1
        return sumpbk / countbk
      else:
        for objectbuild_item in self.objectbuilds.all():
          sumpbk += objectbuild_item.get_objectbuild_ping_price_ab_calculation()
          countbk += 1
        return sumpbk / countbk
    except:
      newlist.append(0)

  def get_regionalHead_username(self):
    return self.finaldecisions.first().regionalHead

  # 判斷是否為兩週內
  def two_weeks(self):
    # 取得目前的日期，要用form dateteim import datetime,不可用import datetime
    today = datetime.now()
    finaldecision_content = self.finaldecisions.first().finalDecision
    auctionDateFirst_day = self.auctions.first().auctionDateFirst
    auctionDateSecond_day = self.auctions.first().auctionDateSecond
    auctionDateThird_day = self.auctions.first().auctionDateThird
    auctionDateFourth_day = self.auctions.first().auctionDateFourth
    if finaldecision_content == "1拍進場" and auctionDateFirst_day != None:
      # 取得要計算的日期，要用form dateteim import datetime,不可用import datetime
      other_day = datetime.strptime(auctionDateFirst_day,'%Y-%m-%d')
      return (other_day-today).days + 1
    elif finaldecision_content == "2拍進場" and auctionDateSecond_day != None:
      # 取得要計算的日期，要用form dateteim import datetime,不可用import datetime
      other_day = datetime.strptime(auctionDateSecond_day,'%Y-%m-%d')
      return (other_day-today).days + 1
    elif finaldecision_content == "3拍進場" and auctionDateThird_day != None:
      # 取得要計算的日期，要用form dateteim import datetime,不可用import datetime
      other_day = datetime.strptime(auctionDateThird_day,'%Y-%m-%d')
      return (other_day-today).days + 1
    elif finaldecision_content == "4拍進場" and auctionDateFourth_day != None:
      # 取得要計算的日期，要用form dateteim import datetime,不可用import datetime
      other_day = datetime.strptime(auctionDateFourth_day,'%Y-%m-%d')
      return (other_day-today).days + 1
    else:
      return ""

  # 取得當前最後一拍對應的底價
  def get_floor_price_from_auction_date(self):
    auctionDateFirst_day = self.auctions.first().auctionDateFirst
    auctionDateSecond_day = self.auctions.first().auctionDateSecond
    auctionDateThird_day = self.auctions.first().auctionDateThird
    auctionDateFourth_day = self.auctions.first().auctionDateFourth
    auctionDateFirst_price = self.auctions.first().auctionFloorPriceFirst
    auctionDateSecond_price = self.auctions.first().auctionFloorPriceSecond
    auctionDateThird_price = self.auctions.first().auctionFloorPriceThird
    auctionDateFourth_price = self.auctions.first().auctionFloorPriceFourth
    if auctionDateFourth_price > 0 and auctionDateFourth_day != "":
      return auctionDateFourth_price
    elif auctionDateThird_price > 0 and auctionDateThird_day != "":
      return auctionDateThird_price
    elif auctionDateSecond_price > 0 and auctionDateSecond_day != "":
      return auctionDateSecond_price
    elif auctionDateFirst_price > 0 and auctionDateFirst_day != "":
      return auctionDateFirst_price
    else:
      return 0

class Land(models.Model):
  yfcase=models.ForeignKey(Yfcase,related_name='lands',on_delete=models.CASCADE)
  landNumber=models.CharField(u'地號',max_length=100,null=True,blank=True)
  landUrl=models.URLField(u'謄本',max_length=200,null=True,blank=True)
  landArea=models.DecimalField(u'地坪(平方公尺)',default=0,max_digits=10,decimal_places=2,null=True,blank=True)
  landHoldingPointPersonal=models.DecimalField(u'個人持分',default=0,max_digits=8,decimal_places=0,null=True,blank=True)
  landHoldingPointAll=models.DecimalField(u'所有持分',default=0,max_digits=8,decimal_places=0,null=True,blank=True)
  landRemarks=models.CharField(u'備註',max_length=100,null=True,blank=True)
  landPresentValue=models.CharField(u'土地現值',max_length=100,null=True,blank=True)
  landTotalArea=models.DecimalField(u'地坪總面積',default=0,max_digits=10,decimal_places=2,null=True,blank=True)
  landAreaWidth=models.DecimalField(u'土地寬度',default=0,max_digits=8,decimal_places=0,null=True,blank=True)
  landAreaDepth=models.DecimalField(u'土地深度',default=0,max_digits=8,decimal_places=0,null=True,blank=True)

  def __str__(self):
    return self.landNumber

  def get_land_holding_point_area(self):
    return self.landArea * ( self.landHoldingPointPersonal / self.landHoldingPointAll)

class Build(models.Model):
  yfcase=models.ForeignKey(Yfcase,related_name='builds',on_delete=models.CASCADE)
  buildNumber=models.CharField(u'建號',max_length=100,null=True,blank=True)
  buildUrl=models.URLField(u'謄本',max_length=200,null=True,blank=True)
  buildArea=models.DecimalField(u'建坪(平方公尺)',default=0,max_digits=10,decimal_places=2,null=True,blank=True)
  buildHoldingPointPersonal=models.DecimalField(u'個人持分',default=0,max_digits=8,decimal_places=0,null=True,blank=True)

templates/yfcase/township_dropdown_list_options.html
<option value="">---------</option>
{% for township in townships %}
<option value="{{ township.pk }}">{{ township.name }}</option>
{% endfor %}

templates/yfcase/yfcase_delete.html
<form action="{% url 'yfcase:yfcase_delete' yfcase.id %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
       <p>你確定要刪除 "{{yfcase.yfcaseCaseNumber}}" ?</p>
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
        <input class="btn btn-success col-md-3" type="submit" value="刪除" />
      </div>

    </div>
  </div>
</form>

templates/yfcase/yfcase_edit.html
{% load widget_tweaks %}

<style type="text/css">
  .help-block{
    color:red;
  }
</style>

<!-- 程式主題的部份 -->
<form action="{% url 'yfcase:yfcase_edit' yfcase.id %}" method="post" id="yfcaseUpdateForm" data-townships-url="{% url 'yfcase:ajax_load_townships' %}" novalidate>{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- body -->
      <div class="modal-body">

        <table>
        <!-- {{ form.as_table }} -->
        </table>

        <input type="hidden" id="user" name="user" value={{author_id}}>
        <!-- {{ form.user|attr:"type:text value:1" }} -->

        <div class="form-group">
          <label for="{{ form.yfcaseCaseNumber.id_for_label }}">{{ form.yfcaseCaseNumber.label }}</label>
          {{ form.yfcaseCaseNumber|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCaseNumber.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseCompany.id_for_label }}">{{ form.yfcaseCompany.label }}</label>
          {{ form.yfcaseCompany|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCompany.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseCity.id_for_label }}">{{ form.yfcaseCity.label }}</label>
          {{ form.yfcaseCity|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCity.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseTownship.id_for_label }}">{{ form.yfcaseTownship.label }}</label>
          {{ form.yfcaseTownship|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseTownship.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseBigSection.id_for_label }}">{{ form.yfcaseBigSection.label }}</label>
          {{ form.yfcaseBigSection|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseBigSection.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseSmallSection.id_for_label }}">{{ form.yfcaseSmallSection.label }}</label>
          {{ form.yfcaseSmallSection|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseSmallSection.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseOtherAddress.id_for_label }}">{{ form.yfcaseOtherAddress.label }}</label>
          {{ form.yfcaseOtherAddress|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseOtherAddress.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseDebtor.id_for_label }}">{{ form.yfcaseDebtor.label }}</label>
          {{ form.yfcaseDebtor|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseDebtor.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseCreditor.id_for_label }}">{{ form.yfcaseCreditor.label }}</label>
          {{ form.yfcaseCreditor|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCreditor.error }}</span>
        </div>

      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">返回</button>
        <input class="btn btn-primary col-md-3" type="submit" value="更新" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  $(document).ready(function() {
    $('#yfcaseUpdateForm').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
      },
      fields: {
        yfcaseCaseNumber: {
          validators: {
            notEmpty: {
              message: '此一欄位不得為空'
            },
            stringLength: {
              min: 5,
              max: 50,
              message: '案件名稱必需介於5-50個文字'
            }
          }
        },
        yfcaseCity: {
          validators: {
            notEmpty: {
              message: '此為必要欄位'
            }
          }
        },
        yfcaseTownship: {
          validators: {
            notEmpty: {
              message: '此為必要欄位'
            }
          }
        },
        yfcaseOtherAddress: {
          validators: {
            notEmpty: {
              message: '此為必要欄位'
            }
          }
        },
        yfcaseCompany: {
          validators: {
            notEmpty: {
              message: '必選欄位'
            }
          }
        }
      }
    });

  });

  // JS觸發事件來使yfcaseCity/yfcaseTownship這兩個欄位動作
  $("#id_yfcaseCity").click(function () {
    var url = $("#yfcaseUpdateForm").attr("data-townships-url");
    var cityId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'city': cityId
      },
      success: function (data) {
        $("#id_yfcaseTownship").html(data);
      }
    });
  });
</script>
{% endblock javascript %}

templates/yfcase/yfcase_new.html
{% load widget_tweaks %}

<style type="text/css">
  .help-block{
    color:red;
  }
</style>


<!-- 程式主題的部份 -->
<form action="{% url 'yfcase:yfcase_new' %}" method="post" id="yfcaseCreateForm" data-townships-url="{% url 'yfcase:ajax_load_townships' %}" >{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">

       <!--  <div class="form-group">
          <label for="{{ form.user.id_for_label }}">{{ form.user.label }}</label>
          {{ form.user|add_class:'form-control' }}
          <span class="help-block">{{ form.user.error }}</span>
        </div>
 -->
        <!-- <input type="text" id="userId" value={{author_id}}> -->

        {{ request.user.id|json_script:"author_id" }} 
        <input type="hidden" id="user" name="user" value={{request.user.id}}>
        <!-- {{ form.user|attr:"type:text value:1" }} -->

        <div class="form-group">
          <label for="{{ form.yfcaseCaseNumber.id_for_label }}">{{ form.yfcaseCaseNumber.label }}</label>
          {{ form.yfcaseCaseNumber|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCaseNumber.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseCompany.id_for_label }}">{{ form.yfcaseCompany.label }}</label>
          {{ form.yfcaseCompany|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCompany.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseCity.id_for_label }}">{{ form.yfcaseCity.label }}</label>
          {{ form.yfcaseCity|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCity.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseTownship.id_for_label }}">{{ form.yfcaseTownship.label }}</label>
          {{ form.yfcaseTownship|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseTownship.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseBigSection.id_for_label }}">{{ form.yfcaseBigSection.label }}</label>
          {{ form.yfcaseBigSection|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseBigSection.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseSmallSection.id_for_label }}">{{ form.yfcaseSmallSection.label }}</label>
          {{ form.yfcaseSmallSection|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseSmallSection.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseOtherAddress.id_for_label }}">{{ form.yfcaseOtherAddress.label }}</label>
          {{ form.yfcaseOtherAddress|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseOtherAddress.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseDebtor.id_for_label }}">{{ form.yfcaseDebtor.label }}</label>
          {{ form.yfcaseDebtor|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseDebtor.error }}</span>
        </div>

        <div class="form-group">
          <label for="{{ form.yfcaseCreditor.id_for_label }}">{{ form.yfcaseCreditor.label }}</label>
          {{ form.yfcaseCreditor|add_class:'form-control' }}
          <span class="help-block">{{ form.yfcaseCreditor.error }}</span>
        </div>
       
      </div>

      <!-- footer -->
      <div class="modal-footer">
        
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">返回</button>
        <input class="btn btn-primary col-md-3" type="submit" value="建立" />
        
      </div>

    </div>
  </div>
</form>


{% block javascript %}
<script>
  $(document).ready(function(){
    // 此為欄位驗証的JS
    $('#yfcaseCreateForm').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
          valid: 'glyphicon glyphicon-ok',
          invalid: 'glyphicon glyphicon-remove',
          validating: 'glyphicon glyphicon-refresh'
      },
      fields: {
          yfcaseCaseNumber: {
            validators: {
              notEmpty: {
                message: '此一欄位不得為空'
              },
              stringLength: {
                min: 5,
                max: 50,
                message: '案件名稱必需介於5-50個文字'
              }
            }
          },
          yfcaseCity: {
            validators: {
              notEmpty: {
                message: '此為必要欄位'
              }
            }
          },
          yfcaseTownship: {
            validators: {
              notEmpty: {
                message: '此為必要欄位'
              }
            }
          },
          yfcaseOtherAddress: {
            validators: {
              notEmpty: {
                message: '此為必要欄位'
              }
            }
          },
          yfcaseCompany: {
            validators: {
              notEmpty: {
                message: '必選欄位'
              }
            }
          }
      }
    });

  });

  // JS觸發事件來使yfcaseCity/yfcaseTownship這兩個欄位動作
  $("#id_yfcaseCity").change(function () {
    var url = $("#yfcaseCreateForm").attr("data-townships-url");
    var cityId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'city': cityId
      },
      success: function (data) {
        $("#id_yfcaseTownship").html(data);
      }
    });
  });

</script>
{% endblock javascript %}